version: '3'

services:
  backend:
    build: ./apps/backend

    volumes:
      - ./apps/backend:/app           
      - /app/node_modules             

    ports:
      - "3001:3001"
    env_file:
      - ./apps/backend/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    command: npm run start:dev       


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./apps/backend/.env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports: ['6379:6379']
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
