version: '3'

services:
  backend:
    build: ./apps/backend
    ports:
      - "3001:3001"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fitness_db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
