export enum NotificationType {
  FOLLOWED = 'FOLLOWED',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  WORKOUT_REMINDER = 'WORKOUT_REMINDER',
  SOCIAL = 'SOCIAL',
  ACHIEVEMENT = 'ACHIEVEMENT',
}
